/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "BeeBotApi": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "DatabaseUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GoogleCloudClientEmail": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GoogleCloudPrivateKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SlackToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
